### ISSUE TITLE
Is that the way suppose to be?

### ISSUE THREAD

**Issue by aymkin** [Roka20012/Roka20012.github.io#1]
No one of the demos seem to be working)

**Comment by Roka20012** [comment]
Hi yeah it`s true
Do you know what it can be?
Any idea to fix it?

**Comment by aymkin** [comment]
0. You need to turn on Github Pages for the repository https://github.com/Roka20012/Roka20012.github.io and web site will be available on https://roka20012.github.io/
1. For repo `Roka20012.github.io` choose "User of Organization site"
http://i.imgur.com/kQzXH3L.png
2. Each llink in this list http://i.imgur.com/yJAme2i.png shoud be a repo, which you turn to `Project Site` http://i.imgur.com/V21M11s.png

**Comment by Roka20012** [comment]
Thanks man I have fixed it :+1:
